### ISSUE TITLE
Interactions with the 300ms delay

### ISSUE THREAD

**Issue by Jonarod** [mathieudutour/react-swipe-to-reveal-options#14]
Hello,

Great component that works well in new browsers like Chrome etc...
However, when testing with my own phone's native browser on Android, I see it still have this (in)famous 300ms delay before throwing the "Click" event.
That being said, I briefly inspected your repo's code and I see it relies on "onTouchStart", "onTouchMove" and "onTouchEnd" to gather this "drag-like" functionality when swiping : (actually calculating position of onTouchMove event, right?). 

The fact is that browsers with 300ms delay result in really poor UX : 
- you touch
- (browser implements 300ms delay)
- you move left or right
- you release touch 
- and THEN it swipes... 

where the expected behaviour should actually be: 
- you touch
- WHILE YOU MOVE (left or Right), the element follows path (or more precisely, it refreshes position of related "event" object)
- you release touch and it stops moving

I tried using your package jointly with the so called [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin) but it only removes 300ms for click events, not for the whole touch/start/move/end pipeline (or I didn't understand how to implement it ?).

Do you have any solution/suggestion to implement your component eliminating the 300ms delay? Or to cut down a bit the problem : is there a way onTouchStart/Move/End could shortCut the browser's default behaviour ? (I tried e.preventDefault() & e.StopPropagation()... it has no effect.)

It's been 3 days I am struggling around this problem and I have two possible conclusions: 
1/ react cannot implement drag actions on browser with 300ms delay for the moment
2/ I am too novice in react to understand how to solve it (high probability)

Thank you !!

**Comment by mathieudutour** [comment]
Have you tried https://github.com/ftlabs/fastclick ?

**Comment by Jonarod** [comment]
Ok I see using `-webkit-transform:translate();` does not solve 300ms problem but it enhances experience a lot for my android browser.
I will give a try to fastclicks.
Thank you for your reply!
P.S: great job and thanks for sharing
