### ISSUE TITLE
example doesn't render on ios 

### ISSUE THREAD

**Issue by brianleroux** [mathieudutour/react-swipe-to-reveal-options#2]
Unable to debug b/c I'm on the go but thought you'd like to know. Likely can reproduce with safari or vanilla WebKit.

**Comment by mathieudutour** [comment]
Hum it's only working with a touch screen for now (or the chrome inspector). Is that what you tried ?

**Comment by brianleroux** [comment]
No, chrome and safari on ios

**Comment by mathieudutour** [comment]
It was a mistake in the transfer of the repo, was still pointing to the old one. Fix now.
