### ISSUE TITLE
Unknown props `onSwipingLeft`, `onSwipingRight`, `delta`, `onSwiped`, `flickThreshold` on <div> tag

### ISSUE THREAD

**Issue by jtham** [mathieudutour/react-swipe-to-reveal-options#21]
I get this warning when using this component with React v15. This warning can be resolved by removing the `onSwipingLeft`, `onSwipingRight`, `delta`, `onSwiped`, `flickThreshold` props when rendering the Swipeable component.

**Comment by vramdal** [comment]
I have submitted a pull request in #22

**Comment by mathieudutour** [comment]
fixed in 0.3.6
