### ISSUE TITLE
reveal options without swiping

### ISSUE THREAD

**Issue by avk** [mathieudutour/react-swipe-to-reveal-options#8]
Swiping works well but I wanted to add another way to show the options typically revealed by swiping. This helps with discoverability.

I had to do something like this in my `onClick` handler:

``` js
  handleClickActions(evt) {
    // without this, touch events would still be triggered and close the options we're trying to reveal
    evt.stopPropagation();
    let toggleButtons = !this.refs.swipeToReveal.state.showRightButtons;
    this.refs.swipeToReveal.setState({
      showRightButtons: toggleButtons
    });
  }
```

The ref `swipeToReveal` points to the component.

Since you have a `close()` method on the component, wouldn't something like the above make sense as a `revealRight()` or `revealLeft()` method?

**Comment by mathieudutour** [comment]
Good idea!
https://github.com/enkidevs/react-swipe-to-reveal-options/commit/f5ca5e0314819cb10bef0ec5da9bf63bf95fe8aa

**Comment by avk** [comment]
Thanks! The new reveals work well, I'm toggling them based on the `showRightButtons` and `showLeftButtons` states. I'll send a PR for a `toggleRight` and `toggleLeft` if that bugs me too much in the long run :)
