### ISSUE TITLE
transitionBackTimeout causes errors on unmount

### ISSUE THREAD

**Issue by avk** [mathieudutour/react-swipe-to-reveal-options#9]
[transitionBackTimeout](https://github.com/enkidevs/react-swipe-to-reveal-options#transitionbacktimeout) seems [to control a `setTimeout` timer](https://github.com/enkidevs/react-swipe-to-reveal-options/blob/d8c2479/react-swipe-to-reveal-options.js#L368) that can error on re-render:

I have a parent component that renders a set of child components, each of which uses `SwipeToRevealOptions`. If the parent component does a `setState` and causes one of the children to be removed, I see the following error:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the SwipeToRevealOptions component.

the backtrace starts with the `setTimeout` in `transitionBack`:
https://github.com/enkidevs/react-swipe-to-reveal-options/blob/d8c2479/react-swipe-to-reveal-options.js#L368

I imagine we need something like a `clearTimeout` in a `componentWillUnmount` to prevent these errors.

**Comment by mathieudutour** [comment]
Indeed, embarrassing :$
https://github.com/enkidevs/react-swipe-to-reveal-options/commit/2adde34cf03fe84f3b444933fff4e4d990dd4e91

**Comment by avk** [comment]
Thanks for the fast response! I upgraded to 0.2.1 but I'm still seeing the error, despite the `clearTimeout`. Worse yet, the actual sliding doesn't seem to be working anymore!

**Comment by mathieudutour** [comment]
oups... Should be fixed

**Comment by avk** [comment]
Thanks! Working now in 0.2.3!
